lib/todo_web/router.ex
defmodule TodoWeb.Router do
  use TodoWeb, :router
  import Phoenix.LiveView.Router

  pipeline :auth do
    plug Todo.Accounts.Pipeline
  end

  pipeline :auth_required do
    plug Guardian.Plug.EnsureAuthenticated
    plug TodoWeb.Plugs.AssignUser
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :dashboard do
    plug :put_layout, {TodoWeb.LayoutView, "dashboard.html"}
  end

  pipeline :live_view do
    plug :put_root_layout, {TodoWeb.LayoutView, :dashboard}
  end

  scope "/", TodoWeb do
    pipe_through [:browser, :auth]

    get "/", HomeController, :index
    get "/login", SessionController, :new
    resources "/users", UserController, only: [:new, :create]
    post "/login", SessionController, :login
    post "/logout", SessionController, :logout

    resources "/reset-password", ResetPasswordTokenController, only: [:new, :create]
    get "/reset-password/reset", ResetPasswordTokenController, :reset
    put "/reset-password/:token", ResetPasswordTokenController, :update
  end

  scope "/", TodoWeb do
    pipe_through [:browser, :auth, :auth_required, :dashboard]

    resources "/users", UserController, only: [:update, :edit]
    resources "/boards", BoardController, only: [:index, :new, :create, :edit, :update]

    resources "/shared-boards/boards", SharedBoard.BoardController,
      only: [:index, :edit, :update],
      name: :shared_board

    resources "/shared-boards/boards/:shared_board_id/list", SharedBoard.ListController,
      only: [:new, :create, :edit, :update],
      name: :shared_board_list

    resources "/boards/:board_id/list", ListController, only: [:new, :create, :edit, :update]

    resources "/share-board", ShareBoardTokenController, only: [:new, :create, :index]
    get "/share-board/activate", ShareBoardTokenController, :activate
  end

  scope "/boards", TodoWeb do
    pipe_through [:browser, :auth, :auth_required, :live_view]

    live "/:id", BoardLiveView
  end

  scope "/shared-boards/boards", TodoWeb do
    pipe_through [:browser, :auth, :auth_required, :live_view]

    live "/:shared_board_id", BoardLiveView
  end

  # Other scopes may use custom stacks.
  # scope "/api", TodoWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TodoWeb.Telemetry
    end
  end
end

lib/todo/boards/board_list.ex
defmodule Todo.Boards.List do
  alias Todo.Boards.{Board, Card}
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  schema "lists" do
    field :name, :string, null: false
    field :archived, :boolean, default: false
    field :position, :integer, null: false

    belongs_to :board, Board, foreign_key: :board_id, type: :binary_id
    has_many :cards, Card

    timestamps()
  end

  @doc false
  def changeset(board, attrs) do
    board
    |> cast(attrs, [:name, :archived, :position])
    |> validate_number(:position, greater_than: 0)
    |> validate_required([:name, :position])
  end
end

lib/todo/boards/board_lists/board_list_manager.ex
defmodule Todo.Boards.Lists.ListManager do
  alias Ecto.Multi
  alias Todo.Boards.{Board, List}
  alias Todo.Boards.Lists.Positions
  alias Todo.Repo
  import Ecto.Query

  @moduledoc """
  This module handles creating and updating lists. When a list is created or updated,
  the positions of the other lists on that board will be re-ordered if required.
  """

  @spec create(%{}, %Board{}) :: {:ok, %List{}} | {:error, String.t()}
  def create(%{"position" => position} = attrs, board) do
    with position <- String.to_integer(position),
         attrs <- validate_updated_list_position(attrs, board.id, position, nil),
         %{valid?: true} = list_changeset <- insert_bl_changeset(attrs, board),
         {:ok, %{list: list}} <-
           insert_list_and_positions(list_changeset, position, board.id) do
      {:ok, list}
    else
      %{valid?: false} ->
        {:error, "Invalid details"}

      _error ->
        {:error, "Unable to create list"}
    end
  end

  @spec update(%{}, %List{}) ::
          {:ok, %List{}} | {:error, String.t()} | {:error, %Ecto.Changeset{}}
  def update(
        %{"position" => updated_position} = attrs,
        %List{board_id: board_id, position: current_position} = list
      ) do
    with updated_position <- String.to_integer(updated_position),
         attrs <-
           validate_updated_list_position(attrs, board_id, updated_position, current_position),
         %{valid?: true} = list_changeset <- update_bl_changeset(attrs, list),
         {:ok, %{list: list}} <-
           update_list_and_positions(
             list_changeset,
             current_position,
             updated_position,
             board_id
           ) do
      {:ok, list}
    else
      %{valid?: false} = changeset ->
        {:error, changeset}

      _error ->
        {:error, "Unable to create list"}
    end
  end

  defp update_list_and_positions(
         list_changeset,
         current_position,
         updated_position,
         board_id
       ) do
    Multi.new()
    |> Multi.merge(fn _ ->
      Positions.reorder(updated_position, current_position, board_id)
    end)
    |> Multi.update(:list, list_changeset)
    |> Repo.transaction()
  end

  defp insert_list_and_positions(list_changeset, position, board_id) do
    Multi.new()
    |> Multi.merge(fn _ ->
      Positions.reorder(position, nil, board_id)
    end)
    |> Multi.insert(:list, list_changeset)
    |> Repo.transaction()
  end

  def insert_bl_changeset(attrs, board) do
    board
    |> Ecto.build_assoc(:lists)
    |> List.changeset(attrs)
  end

  def update_bl_changeset(attrs, list) do
    list
    |> List.changeset(attrs)
  end

  def validate_updated_list_position(attrs, _board_id, updated_position, current_position)
      when updated_position == current_position,
      do: attrs

  # this will compare the highest list position with the updated position. If the updated_position is greater than the highest list position plus 1,
  # it will update the position in the attrs to highest list position + 1. E.g. if updated_position is 10, but the highest list position is 5,
  # then the attrs position will be changed to 6. All other cases will return original attrs.
  def validate_updated_list_position(attrs, board_id, updated_position, _current_position) do
    query =
      from bl in List,
        where: bl.board_id == ^board_id,
        order_by: [desc: bl.position],
        select: bl.position,
        limit: 1

    highest_list_position = Repo.one(query)

    case highest_list_position do
      hlp when hlp == nil -> attrs
      hlp when hlp + 1 >= updated_position -> attrs
      hlp -> %{attrs | "position" => Integer.to_string(hlp + 1)}
    end
  end
end

lib/todo/boards/board_lists/board_list_positions.ex
defmodule Todo.Boards.BoardLists.BoardListPositions do
  import Ecto.Query
  alias Ecto.Multi
  alias Todo.Boards.{BoardList}
  alias Todo.Repo

  defguard is_equal(value1, value2) when value1 == value2 and is_integer(value1) and is_integer(value2)
  defguard is_greater_than(value1, value2) when value1 > value2 and is_integer(value1) and is_integer(value2)

  @moduledoc """
  This modules handles updating the board positions. These are the cases handled:
  - If the updated position and current position are the same, no action is required
  - If there is no list in the updated position, no action is required
  - If the updated position is greater than the current position, then it will reduce
    the positions of the board lists between these values by 1. E.g. If is current position(2)
    and is updated position(5), all lists greater than 2 and less than or equal to 5 will be reduced by 1
  - If the updated position is less than the current position, then it will increase
    the positions of the board lists between these values by 1. E.g. If is current position(6)
    and is updated position(3), all lists greater than or equal to 3 and less than or 6 will be increased by 1
  - All other cases will increase the positions of the lists greater than the updated position
  """

  def reorder(updated_position, current_position, _board_id)
      when is_equal(updated_position, current_position) do
    Multi.new()
  end

  def reorder(updated_position, current_position, board_id) do
    Multi.new()
    |> Multi.run(:board_list_in_updated_position, fn _, _ ->
      board_list_in_updated_position(updated_position, board_id)
    end)
    |> Multi.merge(fn
      %{board_list_in_updated_position: %BoardList{}} ->
        update_positions(updated_position, current_position, board_id)

      %{board_list_in_updated_position: nil} ->
        Multi.new()
    end)
  end

  defp update_positions(updated_position, current_position, board_id)
      when is_greater_than(updated_position, current_position)  do
    query =
      from bl in BoardList,
        where:
          bl.board_id == ^board_id and
          bl.position <= ^updated_position and bl.position > ^current_position,
        update: [set: [position: bl.position - 1]]

    Multi.new()
    |> Multi.update_all(:board_list_positions, query, [])
  end

  defp update_positions(updated_position, current_position, board_id)
      when is_greater_than(current_position, updated_position) do
    query =
      from bl in BoardList,
        where:
          bl.board_id == ^board_id and
          bl.position >= ^updated_position and bl.position < ^current_position,
        update: [set: [position: bl.position + 1]]

    Multi.new()
    |> Multi.update_all(:board_list_positions, query, [])
  end

  defp update_positions(updated_position, _current_position, board_id) do
    query =
      from bl in BoardList,
        where: bl.board_id == ^board_id and bl.position >= ^updated_position,
        update: [set: [position: bl.position + 1]]

    Multi.new()
    |> Multi.update_all(:board_list_positions, query, [])
  end

  def board_list_in_updated_position(updated_position, board_id) do
    query =
      from bl in BoardList,
        where: bl.board_id == ^board_id and bl.position == ^updated_position

    {:ok, Repo.one(query)}
  end
end

lib/todo_web/controllers/board_list_controller.ex
defmodule TodoWeb.BoardListController do
  use TodoWeb, :controller
  alias Todo.{Boards, Boards.BoardList}
  import Guardian.Plug, only: [current_resource: 1]

  def new(conn, %{"board_id" => board_id}) do
    board = Boards.get_board!(board_id, current_resource(conn).id)
    render(conn, "new.html", changeset: Boards.change_board_list(%BoardList{board: board}))
  end

  def create(conn, %{"board_id" => board_id, "board_list" => board_list}) do
    board = Boards.get_board!(board_id, current_resource(conn).id)

    case Boards.create_board_list(board_list, board) do
      {:ok, _multi} ->
        conn
        |> put_flash(:info, "New Board List Created")
        |> redirect(to: "/boards/#{board_id}")

      {:error, error} ->
        conn |> put_flash(:error, error) |> new(%{"board_id" => board_id})
    end
  end

  def edit(conn, %{"board_id" => board_id, "id" => id}) do
    board_list_changeset =
      Boards.get_board_list!(id, board_id, current_resource(conn).id)
      |> Boards.change_board_list()

    render(conn, "edit.html", changeset: board_list_changeset)
  end

  def update(conn, %{"board_list" => attrs, "id" => id, "board_id" => board_id}) do
    case update_board_list(conn, attrs, id, board_id) do
      {:ok, _board} ->
        conn
        |> put_flash(:info, "Board List Updated")
        |> redirect(to: "/boards/#{board_id}")

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:error, "Invalid details.")
        |> render("edit.html", changeset: changeset, id: id)

      {:error, _error} ->
        conn
        |> put_flash(:error, "Oops, something went wrong.")
        |> redirect(to: "/boards/#{board_id}")
    end
  end

  defp update_board_list(conn, attrs, id, board_id) do
    Boards.get_board_list!(id, board_id, current_resource(conn).id)
    |> Boards.update_board_list(attrs)
  end
end

lib/todo_web/views/board_list_view.ex
defmodule TodoWeb.ListView do
  use TodoWeb, :view
end

lib/todo_web/templates/board_list/_board_list.html.eex
<div class="flex w-full max-w-xs p-4 bg-white rounded-md board-list flex-col">
  <ul class="flex flex-col w-full mb-4">
    <li class="my-px">
    <%= link to: Routes.board_list_path(@conn, :edit, @board_list.board_id, @board_list.id), method: :get do %>
      <div class="flex flex-row items-center font-semibold h-12 p-4 rounded-lg text-gray-600 bg-gray-100">
        <span><%= @board_list.name %></span>
        <span class="flex items-center justify-center text-sm text-gray-500 font-semibold bg-gray-200 h-6 px-2 rounded-full ml-auto">0</span>
      </div>
    <% end %>
    </li>
    <div class="border-b-2 mt-3 mb-5"></div>
    <li>
      <div class="border-2 border-gray-200 rounded-lg bg-white mx-auto m-1 p-4 notification-box break-normal">
        <span class="float-right">
          <svg
            class="fill-current text-gray-600"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            width="22"
            height="22"
          >
            <path
              class="heroicon-ui"
              d="M16.24 14.83a1 1 0 0 1-1.41 1.41L12 13.41l-2.83 2.83a1 1 0 0 1-1.41-1.41L10.59 12 7.76 9.17a1 1 0 0 1 1.41-1.41L12 10.59l2.83-2.83a1 1 0 0 1 1.41 1.41L13.41 12l2.83 2.83z"
            />
          </svg>
        </span>
        <div class="text-sm text-gray-800">
          Example card title
        </div>
      </div>
    </li>
  </ul>
  <a class="cursor-pointer">
  <div class="flex font-semibold h-12 p-4 rounded-lg text-gray-600 bg-gray-100 items-center">
    + Add a card
  </div>
  </a>
</div>

lib/todo_web/templates/board_list/edit.html.eex
<%= link "Back to board", to: Routes.live_path(@conn, TodoWeb.BoardLiveView, @changeset.data.board_id), method: :get, class: "pl-6 pt-4 inline-block align-baseline font-bold text-blue-500 hover:text-blue-800" %>
<div class="bg-white rounded-t-lg overflow-hidden p-4 px-3 py-10 bg-gray-200 flex justify-center align-middle h-screen">
  <div class="w-full max-w-xs">
    <h3 class="text-3xl text-center text-gray-800 font-bold py-6 px-4">Update Board List</h3>
    <%= form_for @changeset, Routes.board_list_path(@conn, :update, @changeset.data.board_id, @changeset.data.id), [class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"], fn f -> %>
      <div class="mb-4">
        <%= label f, :name, class: "control-label", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= text_input f, :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline align-middle", placeholder: "john@email.com" %>
      </div>
      <div class="mb-4">
        <%= label f, :position, class: "control-label", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= number_input f, :position, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline align-middle", placeholder: "1" %>
      </div>
      <div class="mb-4 flex items-center">
        <%= checkbox f, :archived, class: "form-checkbox mr-2 text-gray-600" %>
        <%= label f, :archived, class: "text-gray-700 text-sm font-bold" %>
      </div>
      <div class="flex items-center justify-center">
        <%= submit "Update Account", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>
    <% end %>
  </div>
</div>

lib/todo_web/templates/board_list/new.html.eex
<%= link "Back to board", to: Routes.live_path(@conn, TodoWeb.BoardLiveView, @changeset.data.board.id), method: :get, class: "pl-6 pt-4 inline-block align-baseline font-bold text-blue-500 hover:text-blue-800" %>
<div class="bg-white rounded-t-lg overflow-hidden p-4 px-3 py-10 bg-gray-200 flex justify-center align-middle h-screen">
  <div class="w-full max-w-xs">
    <h3 class="text-3xl text-center text-gray-800 font-bold py-6 px-4">New Board List</h3>
    <%= form_for @changeset, Routes.board_list_path(@conn, :create, @changeset.data.board.id), [class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"], fn f -> %>
      <div class="mb-4">
        <%= label f, :name, class: "control-label", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= text_input f, :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline align-middle", placeholder: "Doing" %>
      </div>
      <div class="mb-4">
        <%= label f, :position, class: "control-label", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= number_input f, :position, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline align-middle", placeholder: "1" %>
      </div>
      <div class="flex items-center justify-center">
        <%= submit "Create Board List", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>
    <% end %>
  </div>
</div>