lib/todo_web/router.ex
defmodule TodoWeb.Router do
  use TodoWeb, :router
  import Phoenix.LiveView.Router

  pipeline :auth do
    plug Todo.Accounts.Pipeline
  end

  pipeline :auth_required do
    plug Guardian.Plug.EnsureAuthenticated
    plug TodoWeb.Plugs.AssignUser
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :dashboard do
    plug :put_layout, {TodoWeb.LayoutView, "dashboard.html"}
  end

  pipeline :live_view do
    plug :put_root_layout, {TodoWeb.LayoutView, :dashboard}
  end

  scope "/", TodoWeb do
    pipe_through [:browser, :auth]

    get "/", HomeController, :index
    get "/login", SessionController, :new
    resources "/users", UserController, only: [:new, :create]
    post "/login", SessionController, :login
    post "/logout", SessionController, :logout

    resources "/reset-password", ResetPasswordTokenController, only: [:new, :create]
    get "/reset-password/reset", ResetPasswordTokenController, :reset
    put "/reset-password/:token", ResetPasswordTokenController, :update
  end

  scope "/", TodoWeb do
    pipe_through [:browser, :auth, :auth_required, :dashboard]

    resources "/users", UserController, only: [:update, :edit]
    resources "/boards", BoardController, only: [:index, :new, :create, :edit, :update]

    resources "/shared-boards/boards", SharedBoard.BoardController,
      only: [:index, :edit, :update],
      name: :shared_board

    resources "/shared-boards/boards/:shared_board_id/list", SharedBoard.ListController,
      only: [:new, :create, :edit, :update],
      name: :shared_board_list

    resources "/boards/:board_id/list", ListController, only: [:new, :create, :edit, :update]

    resources "/share-board", ShareBoardTokenController, only: [:new, :create, :index]
    get "/share-board/activate", ShareBoardTokenController, :activate
  end

  scope "/boards", TodoWeb do
    pipe_through [:browser, :auth, :auth_required, :live_view]

    live "/:id", BoardLiveView
  end

  scope "/shared-boards/boards", TodoWeb do
    pipe_through [:browser, :auth, :auth_required, :live_view]

    live "/:shared_board_id", BoardLiveView
  end

  # Other scopes may use custom stacks.
  # scope "/api", TodoWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TodoWeb.Telemetry
    end
  end
end

lib/todo/boards.ex
defmodule Todo.Boards do
  @moduledoc """
  The Boards context.
  """

  import Ecto.Query, warn: false
  alias Todo.Repo
  alias Todo.Boards.{Board, List, Lists.ListManager, Card, BoardUser, ShareBoardToken}

  @doc """
  Returns list of boards for a specific user.

  ## Examples

      iex> list_boards_for_user(123)
      [%Board{}, ...]

  """
  def list_boards_for_user(user_id) do
    from(b in Board,
      where: b.user_id == ^user_id,
      where: b.archived == false,
      order_by: [desc: b.updated_at]
    )
    |> Repo.all()
  end

  @doc """
  Returns list of shared boards for a specific user.

  ## Examples

      iex> list_shared_boards_for_user(123)
      [%Board{}, ...]

  """
  def list_shared_boards_for_user(user_id) do
    from(u in Todo.Accounts.User,
      where: u.id == ^user_id,
      join: shared_boards in assoc(u, :shared_boards),
      on: shared_boards.archived == false,
      select: shared_boards,
      order_by: [desc: shared_boards.updated_at]
    )
    |> Todo.Repo.all()
  end

  @doc """
  Gets a single board without the lists and cards.

  Raises `Ecto.NoResultsError` if the Board does not exist.

  ## Examples

      iex> get_only_board!(123, 12345678)
      %Board{}

      iex> get_only_board!(456, 12345678)
      ** (Ecto.NoResultsError)

  """
  def get_only_board!(id, user_id) do
    query =
      from board in Todo.Boards.Board,
        where: board.id == ^id and board.user_id == ^user_id

    Repo.one!(query)
  end

  @doc """
  Gets a single board with the lists and cards for a user. The lists are ordered by list position.

  Raises `Ecto.NoResultsError` if the Board does not exist.

  ## Examples

      iex> get_board!(123, 12345678)
      %Board{}

      iex> get_board!(456, 12345678)
      ** (Ecto.NoResultsError)

  """
  def get_board!(id, user_id) do
    query =
      from board in Todo.Boards.Board,
        left_join: lists in Todo.Boards.List,
        on: lists.board_id == board.id and lists.archived == false,
        left_join: cards in Todo.Boards.Card,
        on: cards.list_id == lists.id and cards.archived == false,
        where: board.id == ^id and board.user_id == ^user_id,
        order_by: [asc: lists.position, desc: cards.inserted_at],
        preload: [lists: {lists, cards: cards}]

    Repo.one!(query)
  end

  @doc """
  Gets a single shared board without cards or lists.

  Raises `Ecto.NoResultsError` if the Board does not exist.

  ## Examples

      iex> get_only_shared_board!(123, 12345678)
      %Board{}

      iex> get_only_shared_board!(456, 12345678)
      ** (Ecto.NoResultsError)

  """
  def get_only_shared_board!(id, user_id) do
    query =
      from board in Todo.Boards.Board,
        join: board_users in Todo.Boards.BoardUser,
        on: board_users.board_id == ^id and board_users.user_id == ^user_id,
        where: board.id == ^id

    Repo.one!(query)
  end

  @doc """
  Gets a single shared board from the shared boards with the lists and cards for a user. The lists are ordered by list position.

  Raises `Ecto.NoResultsError` if the Board does not exist.

  ## Examples

      iex> get_shared_board!(123, 12345678)
      %Board{}

      iex> get_shared_board!(456, 12345678)
      ** (Ecto.NoResultsError)

  """
  def get_shared_board!(id, user_id) do
    query =
      from board in Todo.Boards.Board,
        join: board_users in Todo.Boards.BoardUser,
        on: board_users.board_id == ^id and board_users.user_id == ^user_id,
        left_join: lists in Todo.Boards.List,
        on: lists.board_id == board.id and lists.archived == false,
        left_join: cards in Todo.Boards.Card,
        on: cards.list_id == lists.id and cards.archived == false,
        where: board.id == ^id,
        order_by: [asc: lists.position, desc: cards.inserted_at],
        preload: [lists: {lists, cards: cards}]

    Repo.one!(query)
  end

  @doc """
  Gets a single list from a board for the user.

  Raises `Ecto.NoResultsError` if the Board does not exist.

  ## Examples

      iex> get_list!(123, 456, 789)
      %Board{}

      iex> get_list!(456, 123, 789)
      ** (Ecto.NoResultsError)

  """
  def get_list!(list_id, board_id, user_id) do
    query =
      from b in Board,
        join: bl in List,
        on: bl.board_id == b.id,
        where:
          b.id == ^board_id and b.user_id == ^user_id and bl.id == ^list_id and
            bl.archived == false,
        select: bl

    Repo.one!(query)
  end

  @doc """
  Gets a single shared board list from a board for the user.

  Raises `Ecto.NoResultsError` if the Board does not exist.

  ## Examples

      iex> get_shared_board_list!(123, 456, 789)
      %Board{}

      iex> get_shared_board_list!(456, 123, 789)
      ** (Ecto.NoResultsError)

  """
  def get_shared_board_list!(list_id, board_id, user_id) do
    query =
      from b in Board,
        join: board_users in Todo.Boards.BoardUser,
        on: board_users.board_id == ^board_id and board_users.user_id == ^user_id,
        join: bl in List,
        on: bl.board_id == b.id,
        where:
          b.id == ^board_id and bl.id == ^list_id and
            bl.archived == false,
        select: bl

    Repo.one!(query)
  end

  @doc """
  Creates a board for a user.

  ## Examples

      iex> create_board(%{field: value}, %User{})
      {:ok, %Board{}}

      iex> create_board(%{field: bad_value}, %User{})
      {:error, %Ecto.Changeset{}}

  """
  def create_board(attrs \\ %{}, user) do
    user
    |> Ecto.build_assoc(:boards)
    |> Board.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a board.

  ## Examples

      iex> update_board(board, %{field: new_value})
      {:ok, %Board{}}

      iex> update_board(board, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_board(%Board{} = board, attrs) do
    board
    |> Board.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Creates a list for a board.

  ## Examples

      iex> create_list(%{field: value}, %Board{})
      {:ok, %List{}}

      iex> create_list(%{field: bad_value}, %Board{})
      {:error, "error message"}

  """
  def create_list(attrs \\ %{}, board) do
    ListManager.create(attrs, board)
  end

  @doc """
  Updates a list.

  ## Examples

      iex> update_list(list, %{field: new_value})
      {:ok, %Board{}}

      iex> update_list(list, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_list(%List{} = list, attrs) do
    ListManager.update(attrs, list)
  end

  @doc """
  Creates a card for a list.

  ## Examples

      iex> create_card(%{field: value}, %Card{})
      {:ok, %Board{}}

      iex> create_card(%{field: bad_value}, %Card{})
      {:error, %Ecto.Changeset{}}

  """
  def create_card(attrs \\ %{}, list) do
    list
    |> Ecto.build_assoc(:cards)
    |> Card.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking board changes.

  ## Examples

      iex> change_board(board)
      %Ecto.Changeset{data: %Board{}}

  """
  def change_board(%Board{} = board, attrs \\ %{}) do
    Board.changeset(board, attrs)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking list changes.

  ## Examples

      iex> change_list(list)
      %Ecto.Changeset{data: %List{}}

  """
  def change_list(%List{} = list, attrs \\ %{}) do
    List.changeset(list, attrs)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking card changes.

  ## Examples

      iex> change_card(card)
      %Ecto.Changeset{data: %Card{}}

  """
  def change_card(%Card{} = card, attrs \\ %{}) do
    Card.changeset(card, attrs)
  end

  @doc """
  Updates a card.

  ## Examples

      iex> update_card(card, %{field: new_value})
      {:ok, %Board{}}

      iex> update_card(card, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_card(%Card{} = card, attrs) do
    card
    |> Card.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Creates a board user.

  ## Examples

      iex> create_board_user("1234", "5678")
      {:ok, %BoardUser{}}

      iex> create_board_user("1234", "5678")
      {:error, %Ecto.Changeset{}}

  """
  def create_board_user(user_id, board_id) do
    BoardUser.changeset(%Todo.Boards.BoardUser{}, %{user_id: user_id, board_id: board_id})
    |> Repo.insert()
  end

  @doc """
  Creates a share board token.

  ## Examples

      iex> create_share_board_token("1234", "5678")
      {:ok, %ShareBoardToken{}}

      iex> create_share_board_token("1234", "5678")
      {:error, %Ecto.Changeset{}}

  """
  def create_share_board_token(board_id, user_id) do
    expiry_date = Timex.now() |> Timex.shift(days: 1)

    ShareBoardToken.changeset(%ShareBoardToken{}, %{
      user_id: user_id,
      board_id: board_id,
      token: create_token(),
      expiry_date: expiry_date
    })
    |> Repo.insert()
  end

  defp create_token do
    :crypto.strong_rand_bytes(30)
    |> Base.encode64(padding: false)
    |> String.replace(["+", "/"], "")
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking share board token changes.

  ## Examples

      iex> change_share_board_token(board)
      %Ecto.Changeset{data: %ShareBoardToken{}}

  """
  def change_share_board_token(%ShareBoardToken{} = share_board_token, attrs \\ %{}) do
    ShareBoardToken.changeset(share_board_token, attrs)
  end
end

lib/todo/boards/board.ex
defmodule Todo.Boards.Board do
  alias Todo.{Accounts.User, Boards.List}
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  schema "boards" do
    field :name, :string, null: false
    field :archived, :boolean, default: false

    belongs_to :user, User, foreign_key: :user_id, type: :binary_id
    has_many :lists, List
    has_many :board_users, Todo.Boards.BoardUser
    has_many :shared_boards_users, through: [:board_users, :board]

    timestamps()
  end

  @doc false
  def changeset(board, attrs) do
    board
    |> cast(attrs, [:name, :archived])
    |> validate_required([:name])
  end
end

lib/todo/boards/board_list.ex
defmodule Todo.Boards.List do
  alias Todo.Boards.{Board, Card}
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  schema "lists" do
    field :name, :string, null: false
    field :archived, :boolean, default: false
    field :position, :integer, null: false

    belongs_to :board, Board, foreign_key: :board_id, type: :binary_id
    has_many :cards, Card

    timestamps()
  end

  @doc false
  def changeset(board, attrs) do
    board
    |> cast(attrs, [:name, :archived, :position])
    |> validate_number(:position, greater_than: 0)
    |> validate_required([:name, :position])
  end
end

lib/todo/boards/board_user.ex
defmodule Todo.Boards.BoardUser do
  alias Todo.{Accounts.User, Boards.Board}
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  schema "board_users" do
    belongs_to :user, User, foreign_key: :user_id, type: :binary_id
    belongs_to :board, Board, foreign_key: :board_id, type: :binary_id

    timestamps()
  end

  @doc false
  def changeset(board_user, attrs) do
    board_user
    |> cast(attrs, [:user_id, :board_id])
    |> validate_required([:user_id, :board_id])
    |> assoc_constraint(:user)
    |> assoc_constraint(:board)
  end
end

lib/todo_web/controllers/board_controller.ex
defmodule TodoWeb.BoardController do
  use TodoWeb, :controller
  alias Todo.{Boards, Boards.Board}
  import Guardian.Plug, only: [current_resource: 1]

  def new(conn, _params) do
    render(conn, "new.html", changeset: Boards.change_board(%Board{}))
  end

  def index(conn, _params) do
    render(conn, "index.html", boards: user_boards(conn))
  end

  def create(conn, %{"board" => board}) do
    case Boards.create_board(board, current_resource(conn)) do
      {:ok, _board} ->
        conn
        |> put_flash(:info, "Board Created")
        |> render("index.html", boards: user_boards(conn))

      {:error, _changeset} ->
        conn |> put_flash(:error, "Oops, something went wrong.") |> new(%{})
    end
  end

  def edit(conn, %{"id" => id}) do
    changeset = Boards.change_board(get_board(conn, id))
    render(conn, "edit.html", changeset: changeset, id: id)
  end

  def update(conn, %{"board" => attrs, "id" => id}) do
    case update_board(conn, attrs, id) do
      {:ok, _board} ->
        conn
        |> put_flash(:info, "Board Updated")
        |> redirect(to: "/boards")

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:error, "Invalid details.")
        |> render("edit.html", changeset: changeset, id: id)

      {:error, _error} ->
        conn
        |> put_flash(:error, "Oops, something went wrong.")
        |> render("index.html", boards: user_boards(conn))
    end
  end

  defp user_boards(conn) do
    Boards.list_boards_for_user(current_resource(conn).id)
  end

  defp get_board(conn, id) do
    Boards.get_board!(id, current_resource(conn).id)
  end

  defp update_board(conn, attrs, id) do
    case get_board(conn, id) do
      nil -> {:error, %Board{}}
      board -> Boards.update_board(board, attrs)
    end
  end
end

lib/todo_web/controllers/shared_board/board_controller.ex
defmodule TodoWeb.SharedBoard.BoardController do
  use TodoWeb, :controller
  alias Todo.{Boards, Boards.Board}
  import Guardian.Plug, only: [current_resource: 1]

  def index(conn, _params) do
    render(conn, "index.html", boards: user_boards(conn))
  end

  def edit(conn, %{"id" => id}) do
    changeset = Boards.change_board(get_board(conn, id))
    render(conn, "edit.html", changeset: changeset, id: id)
  end

  def update(conn, %{"board" => attrs, "id" => id}) do
    case update_board(conn, attrs, id) do
      {:ok, _board} ->
        conn
        |> put_flash(:info, "Board Updated")
        |> redirect(to: "/shared-boards/boards")

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:error, "Invalid details.")
        |> render("edit.html", changeset: changeset, id: id)

      {:error, _error} ->
        conn
        |> put_flash(:error, "Oops, something went wrong.")
        |> render("index.html", boards: user_boards(conn))
    end
  end

  defp get_board(conn, id) do
    Boards.get_shared_board!(id, current_resource(conn).id)
  end

  defp user_boards(conn) do
    Boards.list_shared_boards_for_user(current_resource(conn).id)
  end

  defp update_board(conn, attrs, id) do
    case get_board(conn, id) do
      nil -> {:error, %Board{}}
      board -> Boards.update_board(board, attrs)
    end
  end
end

lib/todo_web/views/board_view.ex
defmodule TodoWeb.BoardView do
  use TodoWeb, :view
end

lib/todo_web/views/shared_board/board_view.ex
defmodule TodoWeb.SharedBoard.BoardView do
  use TodoWeb, :view
end

lib/todo_web/templates/board/archive_board_component.html.leex
<div id="archive-board-modal-overlay" class="<%= assigns.modal_state %> fixed z-10 inset-0 overflow-y-auto">
  <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
    <div class="fixed inset-0 transition-opacity">
      <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
    </div>
    <span class="hidden sm:inline-block sm:align-middle sm:h-screen"></span>
    <div id="archive-board-modal" class="modal inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full" role="dialog" aria-modal="true" aria-labelledby="modal-headline">
      <div class="flex justify-end mx-4 mt-4">
      <div phx-click="hide-archive-board-component" phx-target="<%= @myself %>" class="cursor-pointer mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-full hover:bg-gray-200 sm:mx-0 sm:h-10 sm:w-10">
        <svg class="fill-current text-gray-500" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
          <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
        </svg>
      </div>
      </div>
      <h2 class="text-lg font-semibold h-12 p-2 rounded-lg text-gray-900 text-center">Are you sure you want to archive this board?</h2>
      <div class="bg-white px-4 pb-8">
        <div class="flex justify-center">
          <div class="flex items-center justify-center mt-6">
            <%= form_for assigns.changeset, "#", [phx_submit: :update, phx_target: @myself, id: "archive-board-form"], fn f -> %>
              <%= hidden_input f, :archived, value: true %>
              <div class="flex items-center justify-center">
                <%= submit "Archive Board", phx_disable_with: "Archiving Board", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

lib/todo_web/templates/board/edit.html.eex
<%= link "Back to board", to: Routes.live_path(@conn, TodoWeb.BoardLiveView, @id), method: :get, class: "pl-6 pt-4 inline-block align-baseline font-bold text-blue-500 hover:text-blue-800" %>
<div class="bg-white rounded-t-lg overflow-hidden p-4 px-3 py-10 bg-gray-200 flex justify-center align-middle h-screen">
  <div class="w-full max-w-xs">
    <h3 class="text-3xl text-center text-gray-800 font-bold py-6 px-4">Update Board</h3>
    <%= form_for @changeset, Routes.board_path(@conn, :update, @id), [class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"], fn f -> %>
      <div class="mb-4">
        <%= label f, :name, class: "control-label", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= text_input f, :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline align-middle", placeholder: "john@email.com" %>
      </div>
      <div class="flex items-center justify-center">
        <%= submit "Update Account", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>
    <% end %>
  </div>
</div>

lib/todo_web/templates/board/index.html.eex
<div class="flex items-center flex-col">
  <h2 class="text-gray-800 text-3xl font-semibold my-6 boards-header">Boards</h2>
  <%= link "New Board", to: Routes.board_path(@conn, :new), method: :get, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
  <div class="flex justify-center flex-wrap w-9/12 mt-12">
    <%= for board <- @boards do %>
      <div class="w-full px-2 md:w-1/4 mb-4 h-32 max-w">
        <%= link(board.name, to: "/boards/#{board.id}", method: :get, class: "hover:bg-gray-100 w-full h-full bg-white shadow-lg rounded-lg flex items-center justify-center px-2 text-gray-800 text-xl text-center font-semibold text-align") %>
      </div>
    <% end %>
  </div>
</div>

lib/todo_web/templates/board/new.html.eex
<div class="bg-white rounded-t-lg overflow-hidden p-4 px-3 py-10 bg-gray-200 flex justify-center align-middle h-screen">
  <div class="w-full max-w-xs">
    <h3 class="text-3xl text-center text-gray-800 font-bold py-6 px-4">New Board</h3>
    <%= form_for @changeset, Routes.board_path(@conn, :create), [class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"], fn f -> %>
      <div class="mb-4">
        <%= label f, :name, class: "control-label", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= text_input f, :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline align-middle", placeholder: "Todo List" %>
      </div>
      <div class="flex items-center justify-center">
        <%= submit "Create Board", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>
    <% end %>
  </div>
</div>

lib/todo_web/templates/board/show.html.leex
<%= if assigns.board.archived do %>
  <h2 class="text-center font-medium mt-10 text-2xl"><%= assigns.board.name %> has been archived</h2>
<% else %>
  <div class="flex items-center flex-col mb-16">
    <h2 class="text-gray-800 text-3xl font-semibold my-6"><%= assigns.board.name %></h2>
    <div class="flex">
      <%= link "Edit Board", to: assigns.edit_board_link, method: :get, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-2" %>
      <%= live_component @socket, TodoWeb.ArchiveBoardComponent, id: assigns.board.id, board: assigns.board %>
      <%= if assigns.show_archive_board_link do %>
        <div phx-click="display-archive-board-component" phx-value-id="<%= assigns.board.id %>" id="archive-board-<%= assigns.board.id %>" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline mr-2 cursor-pointer">
          Archive Board
        </div>
      <% end %>
      <%= link "Add New List", to: assigns.new_list_link, method: :get, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
    </div>
  </div>
  <div class="w-full h-full px-6">
    <div class="flex h-full" id="lists">
      <%= for list <- assigns.board.lists do %>
        <%= live_component @socket, TodoWeb.ListComponent, id: list.id, list: list, user_id: assigns.user.id, lists: assigns.board.lists, edit_list_path: assigns.edit_list_path %>
      <% end %>
    </div>
  </div>
<% end %>