lib/todo_web/router.ex
defmodule TodoWeb.Router do
  use TodoWeb, :router
  import Phoenix.LiveView.Router

  pipeline :auth do
    plug Todo.Accounts.Pipeline
  end

  pipeline :auth_required do
    plug Guardian.Plug.EnsureAuthenticated
    plug TodoWeb.Plugs.AssignUser
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :dashboard do
    plug :put_layout, {TodoWeb.LayoutView, "dashboard.html"}
  end

  pipeline :live_view do
    plug :put_root_layout, {TodoWeb.LayoutView, :dashboard}
  end

  scope "/", TodoWeb do
    pipe_through [:browser, :auth]

    get "/", HomeController, :index
    get "/login", SessionController, :new
    resources "/users", UserController, only: [:new, :create]
    post "/login", SessionController, :login
    post "/logout", SessionController, :logout

    resources "/reset-password", ResetPasswordTokenController, only: [:new, :create]
    get "/reset-password/reset", ResetPasswordTokenController, :reset
    put "/reset-password/:token", ResetPasswordTokenController, :update
  end

  scope "/", TodoWeb do
    pipe_through [:browser, :auth, :auth_required, :dashboard]

    resources "/users", UserController, only: [:update, :edit]
    resources "/boards", BoardController, only: [:index, :new, :create, :edit, :update]

    resources "/shared-boards/boards", SharedBoard.BoardController,
      only: [:index, :edit, :update],
      name: :shared_board

    resources "/shared-boards/boards/:shared_board_id/list", SharedBoard.ListController,
      only: [:new, :create, :edit, :update],
      name: :shared_board_list

    resources "/boards/:board_id/list", ListController, only: [:new, :create, :edit, :update]

    resources "/share-board", ShareBoardTokenController, only: [:new, :create, :index]
    get "/share-board/activate", ShareBoardTokenController, :activate
  end

  scope "/boards", TodoWeb do
    pipe_through [:browser, :auth, :auth_required, :live_view]

    live "/:id", BoardLiveView
  end

  scope "/shared-boards/boards", TodoWeb do
    pipe_through [:browser, :auth, :auth_required, :live_view]

    live "/:shared_board_id", BoardLiveView
  end

  # Other scopes may use custom stacks.
  # scope "/api", TodoWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TodoWeb.Telemetry
    end
  end
end

lib/todo/accounts/reset_password_token.ex
defmodule Todo.Accounts.ResetPasswordToken do
  use Ecto.Schema
  import Ecto.Changeset
  alias Todo.Accounts.User
  alias Todo.Repo

  @primary_key {:id, :binary_id, autogenerate: true}
  schema "reset_password_tokens" do
    field :token, :string, null: false
    field :expiry_date, :utc_datetime, null: false
    field :used, :boolean, null: false, default: false

    belongs_to :user, User, foreign_key: :user_id, type: :binary_id

    timestamps()
  end

  @doc false
  def changeset(reset_password_token, attrs) do
    reset_password_token
    |> cast(attrs, [:user_id, :token, :expiry_date, :used])
    |> validate_required([:user_id, :token, :expiry_date])
    |> assoc_constraint(:user)
  end

  def validate(token) do
    with %__MODULE__{} = reset_password_token <- get_reset_password_token(token),
         true <- not_expired?(reset_password_token),
         true <- not_used?(reset_password_token) do
      {:ok, reset_password_token}
    else
      {false, error} -> {:error, error}
      _ -> {:error, "Reset password link is invalid."}
    end
  end

  defp get_reset_password_token(token) do
    Todo.Repo.get_by(__MODULE__, token: token) |> Repo.preload(:user)
  end

  defp not_expired?(share_board_token) do
    case DateTime.compare(share_board_token.expiry_date, Timex.now()) do
      :lt -> {false, "Reset password link has expired."}
      _ -> true
    end
  end

  defp not_used?(reset_password_token) do
    case !reset_password_token.used do
      false -> {false, "Reset password link has already been used."}
      true -> true
    end
  end
end

lib/todo/accounts/reset_password_token/create_reset_password_token.ex
defmodule Todo.Accounts.ResetPasswordToken.CreateResetPasswordToken do
  alias Todo.{Accounts, Accounts.User}
  alias Todo.Workers.ResetPasswordEmailWorker
  alias Todo.Repo

  def create(email) do
    with {:ok, user} <- get_user(email),
         {:ok, reset_password_token} <- Accounts.create_reset_password_token(user.id),
         {:ok, _} <- enqueue_reset_password_email_worker(reset_password_token.token) do
      {:ok, reset_password_token}
    else
      {:error, error} -> {:error, error}
      _ -> {:error, "Unable to send reset password email"}
    end
  end

  defp get_user(email) do
    case Repo.get_by(User, email: email) do
      nil -> {:error, "User does not exist."}
      user -> {:ok, user}
    end
  end

  defp enqueue_reset_password_email_worker(token) do
    ResetPasswordEmailWorker.enqueue(token)
  end
end

lib/todo_web/controllers/reset_password_token_controller.ex
defmodule TodoWeb.ResetPasswordTokenController do
  use TodoWeb, :controller
  alias Todo.Accounts
  alias Ecto.Multi
  alias Todo.Accounts.{ResetPasswordToken, ResetPasswordToken.CreateResetPasswordToken}

  def new(conn, _params) do
    render_new(conn)
  end

  def create(conn, %{"reset_password_token" => %{"email" => email}}) do
    with {:ok, _} <- CreateResetPasswordToken.create(email) do
      conn
      |> put_flash(:info, "Reset password email has been sent to #{email}")
      |> render_new
    else
      {:error, message} ->
        conn
        |> put_flash(:error, message)
        |> render_new
    end
  end

  def reset(conn, %{"token" => token}) do
    with {:ok, %ResetPasswordToken{user: user}} <- ResetPasswordToken.validate(token) do
      conn
      |> render("reset.html", changeset: Accounts.change_user(user), token: token)
    else
      {:error, message} ->
        conn
        |> put_flash(:error, message)
        |> render_new
    end
  end

  def update(conn, %{"token" => token, "user" => %{"password" => new_password}}) do
    with {:ok, reset_password_token} <- ResetPasswordToken.validate(token),
         {:ok, _} <- update_user_and_reset_password_token(reset_password_token, new_password) do
      conn
      |> put_flash(:info, "Password has been reset.")
      |> redirect(to: "/login")
    else
      {:error, message} ->
        conn
        |> put_flash(:error, message)
        |> render_new
    end
  end

  defp render_new(conn) do
    render(conn, "new.html",
      changeset: Accounts.change_reset_password_token(%ResetPasswordToken{})
    )
  end

  defp update_user_and_reset_password_token(reset_password_token, new_password) do
    Multi.new()
    |> Multi.update(
      :reset_password_token,
      Accounts.change_reset_password_token(reset_password_token, %{used: true})
    )
    |> Multi.update(
      :user,
      Accounts.change_user(reset_password_token.user, %{password: new_password})
    )
    |> Todo.Repo.transaction()
  end
end

lib/todo_web/views/reset_password_token_view.ex
defmodule TodoWeb.ResetPasswordTokenView do
  use TodoWeb, :view
end

lib/todo_web/templates/reset_password_token/new.html.eex
<div class="bg-white rounded-t-lg overflow-hidden p-4 px-3 py-10 bg-gray-200 flex justify-center align-middle h-screen">
  <div class="w-full max-w-xs">
    <h3 class="text-3xl text-center text-gray-800 font-bold py-6 px-4 ">Reset Password</h3>
    <%= form_for @changeset, Routes.reset_password_token_path(@conn, :create), [class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"], fn f -> %>
      <div class="mb-6">
        <label class="control-label block text-gray-700 text-sm font-bold mb-2" for="card_description">Email</label>
        <%= email_input f, :email, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "john@email.com" %>
      </div>
      <div class="flex items-center justify-center">
        <%= submit "Reset Pasword", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>
    <% end %>
  </div>
</div>

lib/todo_web/templates/reset_password_token/reset.html.eex
<div class="bg-white rounded-t-lg overflow-hidden p-4 px-3 py-10 bg-gray-200 flex justify-center align-middle h-screen">
  <div class="w-full max-w-xs">
    <h3 class="text-3xl text-center text-gray-800 font-bold py-6 px-4 ">Update Password</h3>
    <%= form_for @changeset, Routes.reset_password_token_path(@conn, :update, @token), [class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"], fn f -> %>
      <div class="mb-6">
        <%= label f, :password, class: "control-label", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= password_input f, :password, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "******************" %>
      </div>
      <div class="flex items-center justify-center">
        <%= submit "Reset Pasword", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>
    <% end %>
  </div>
</div>